language: node_js
node_js:
  - 10

jobs:
  include:
    - script: bash ./tutorials/run-tests.sh
      name: "Community Tutorials Tests"
    - script: bash ./toolkits/landcover/run-tests.sh
      name: "Landcover Toolkit Tests"
