language: node_js
node_js:
  - 10

jobs:
  include:
    - stage: "Community Tutorials"
      name: "tutorials"
      before_install:
        - cd tutorials
      install:
        - npm install
      script:
        - npm run test
    - stage: "Landcover Toolkit"
      name: "landcover-toolkit"
      before_install:
        - cd toolkits/landcover
        - openssl aes-256-cbc -K $encrypted_b99e9b2db4c0_key -iv $encrypted_b99e9b2db4c0_iv -in test/.private-key.json.enc -out toolkits/landcover/test/.private-key.json -d
      install:
        - npm install
      script:
        - npm run test
